package sparql

import (
	"slices"
	"strings"

	rdflibgo "github.com/tggo/goRDFlib"
)

// internalVarMark starts the name of every variable the parser generates for
// [] blank nodes (".bnodeN"), collections (".collN") and reifiers
// (".reifierN"). '.' cannot start a VARNAME (grammar [166]), so no query can
// write such a variable, and ?_x stays an ordinary user variable.
const internalVarMark = "."

// isInternalVar reports whether a variable name (without '?') was generated by
// the parser.
func isInternalVar(name string) bool {
	return strings.HasPrefix(name, internalVarMark)
}

// selectStarVars returns the variables of SELECT *: every variable in scope in
// the WHERE pattern (SPARQL 1.1 §18.2.1, §16.1.1), whether or not a solution
// binds it, plus any other user variable a solution carries (pre-bound
// values). Parser-generated variables are left out. The result is sorted.
func selectStarVars(where Pattern, solutions []map[string]rdflibgo.Term) []string {
	set := make(map[string]bool)
	addInScopeVars(where, set)
	for _, s := range solutions {
		for k := range s {
			set[k] = true
		}
	}
	vars := make([]string, 0, len(set))
	for v := range set {
		if !isInternalVar(v) {
			vars = append(vars, v)
		}
	}
	slices.Sort(vars)
	return vars
}

// addInScopeVars adds the in-scope variables of a pattern per the table in
// SPARQL 1.1 §18.2.1.
func addInScopeVars(p Pattern, set map[string]bool) {
	switch pat := p.(type) {
	case *BGP:
		for _, t := range pat.Triples {
			addTermVars(t.Subject, set)
			addTermVars(t.Predicate, set)
			addTermVars(t.Object, set)
		}
	case *JoinPattern:
		addInScopeVars(pat.Left, set)
		addInScopeVars(pat.Right, set)
	case *OptionalPattern:
		addInScopeVars(pat.Main, set)
		addInScopeVars(pat.Optional, set)
	case *UnionPattern:
		addInScopeVars(pat.Left, set)
		addInScopeVars(pat.Right, set)
	case *MinusPattern:
		addInScopeVars(pat.Left, set) // MINUS adds nothing from its right side
	case *FilterPattern:
		addInScopeVars(pat.Pattern, set)
	case *BindPattern:
		addInScopeVars(pat.Pattern, set)
		set[pat.Var] = true
	case *ValuesPattern:
		for _, v := range pat.Vars {
			set[v] = true
		}
	case *GraphPattern:
		addTermVars(pat.Name, set)
		addInScopeVars(pat.Pattern, set)
	case *SubqueryPattern:
		q := pat.Query
		if q.Variables == nil { // SELECT * in the subquery
			addInScopeVars(q.Where, set)
			return
		}
		for _, v := range q.Variables {
			set[v] = true
		}
		for _, pe := range q.ProjectExprs {
			set[pe.Var] = true
		}
	}
}

// addTermVars adds the variables of a pattern term: a variable itself, or the
// variables inside a triple term "<<( s p o )>>".
func addTermVars(s string, set map[string]bool) {
	if strings.HasPrefix(s, "?") {
		set[s[1:]] = true
		return
	}
	if strings.HasPrefix(s, "<<( ") && strings.HasSuffix(s, " )>>") {
		for _, part := range splitTripleTermParts(s[4 : len(s)-4]) {
			addTermVars(part, set)
		}
	}
}
