package sparql

import (
	"slices"
	"strings"

	rdflibgo "github.com/tggo/goRDFlib"
)

// internalVarMark starts the name of every variable the parser generates for
// [] blank nodes (".bnodeN"), collections (".collN") and reifiers
// (".reifierN"). '.' cannot start a VARNAME (grammar [166]), so no query can
// write such a variable, and ?_x stays an ordinary user variable.
const internalVarMark = "."

// isInternalVar reports whether a variable name (without '?') was generated by
// the parser.
func isInternalVar(name string) bool {
	return strings.HasPrefix(name, internalVarMark)
}

// selectStarVars returns the variables of SELECT *: every variable in scope in
// the WHERE pattern (SPARQL 1.1 §18.2.1, §16.1.1), whether or not a solution
// binds it, plus any other user variable a solution carries (pre-bound
// values). Parser-generated variables are left out.
//
// Variables come in the order they first appear in the query, which is the
// order every W3C expected result uses (csv-tsv-res, for one) and what users
// see in other engines. Variables that appear only in solutions (pre-bound)
// follow, sorted, so the list is deterministic.
func selectStarVars(where Pattern, solutions []map[string]rdflibgo.Term) []string {
	set := &orderedVars{seen: make(map[string]bool)}
	addInScopeVars(where, set)
	var extra []string
	for _, s := range solutions {
		for k := range s {
			if !set.seen[k] {
				set.seen[k] = true
				extra = append(extra, k)
			}
		}
	}
	slices.Sort(extra)
	vars := make([]string, 0, len(set.order)+len(extra))
	for _, v := range append(set.order, extra...) {
		if !isInternalVar(v) {
			vars = append(vars, v)
		}
	}
	return vars
}

// orderedVars is a set of variable names that remembers insertion order.
type orderedVars struct {
	seen  map[string]bool
	order []string
}

func (o *orderedVars) add(v string) {
	if !o.seen[v] {
		o.seen[v] = true
		o.order = append(o.order, v)
	}
}

// addInScopeVars adds the in-scope variables of a pattern per the table in
// SPARQL 1.1 §18.2.1.
func addInScopeVars(p Pattern, set *orderedVars) {
	switch pat := p.(type) {
	case *BGP:
		for _, t := range pat.Triples {
			addTermVars(t.Subject, set)
			addTermVars(t.Predicate, set)
			addTermVars(t.Object, set)
		}
	case *JoinPattern:
		addInScopeVars(pat.Left, set)
		addInScopeVars(pat.Right, set)
	case *OptionalPattern:
		addInScopeVars(pat.Main, set)
		addInScopeVars(pat.Optional, set)
	case *UnionPattern:
		addInScopeVars(pat.Left, set)
		addInScopeVars(pat.Right, set)
	case *MinusPattern:
		addInScopeVars(pat.Left, set) // MINUS adds nothing from its right side
	case *FilterPattern:
		addInScopeVars(pat.Pattern, set)
	case *BindPattern:
		addInScopeVars(pat.Pattern, set)
		set.add(pat.Var)
	case *ValuesPattern:
		for _, v := range pat.Vars {
			set.add(v)
		}
	case *GraphPattern:
		addTermVars(pat.Name, set)
		addInScopeVars(pat.Pattern, set)
	case *SubqueryPattern:
		q := pat.Query
		if q.Variables == nil { // SELECT * in the subquery
			addInScopeVars(q.Where, set)
			return
		}
		for _, v := range q.Variables {
			set.add(v)
		}
		for _, pe := range q.ProjectExprs {
			set.add(pe.Var)
		}
	}
}

// addTermVars adds the variables of a pattern term: a variable itself, or the
// variables inside a triple term "<<( s p o )>>".
func addTermVars(s string, set *orderedVars) {
	if strings.HasPrefix(s, "?") {
		set.add(s[1:])
		return
	}
	if strings.HasPrefix(s, "<<( ") && strings.HasSuffix(s, " )>>") {
		for _, part := range splitTripleTermParts(s[4 : len(s)-4]) {
			addTermVars(part, set)
		}
	}
}
